project:
  type: website
  output-dir: docs

website:
  favicon: images/favicon.ico
  site-url: "christianjmills.com"
  description: "My personal blog"
  title: "Christian Mills"
  image: images/logo.png
  navbar:
    background: dark
    right:
      # - icon: file-person-fill
        # href: ./about.html
      - about.qmd
      - icon: envelope-fill
        href: mailto:christian@christianjmills.com
      - icon: github
        href: https://github.com/cj-mills
      - icon: twitter
        href: https://twitter.com/cdotjdotmills
      - icon: rss
        href: index.xml
  page-navigation: true
  page-footer: 
    center: 
      - text: "Copyright 2022, Christian J. Mills"
    # left:
    #   - icon: envelope-fill
    #     href: mailto:christian@christianjmills.com
    #   - icon: github
    #     href: https://github.com/cj-mills
    #   - icon: twitter
    #     href: https://twitter.com/cdotjdotmills
    #   - icon: rss
    #     href: index.xml
    # border: false
    background: dark
      
  twitter-card:
    creator: "@cdotjdotmills"
    site: "@cdotjdotmills"
    image: images/logo.png
  open-graph:
    image: images/logo.png

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css



