project:
  type: website
  # output-dir: docs

website:
  cookie-consent: false
  favicon: images/favicon.ico
  site-url: "https://christianjmills.com"
  description: "This is Christian Mills' personal Blog."
  title: "Christian Mills"
  image: images/logo.png
  navbar:
    background: dark
    right:
      - text: "Blog"
        file: blog.qmd
      - text: "Tutorials"
        file: series/tutorials/index.md
      - text: "Notes"
        file: series/notes/index.md
      # - icon: file-person-fill
        # href: ./about.html
      # - text: "Services"
      #   file: services.qmd
      - about.qmd
      - icon: envelope-fill
        href: mailto:christian@christianjmills.com
      - icon: github
        href: https://github.com/cj-mills
      # - icon: twitter
      #   href: https://twitter.com/cdotjdotmills
      - icon: linkedin
        href: https://www.linkedin.com/in/christianjmills
      # - icon: discord
      #   href: 
      - icon: rss
        href: blog.xml
  page-navigation: true
  page-footer: 
    center: 
      - text: "© 2024 Christian J. Mills"
        href: about.qmd
    left:
      # - text: Content licensed under CC BY-NC-ND 4.0
      #   href: https://creativecommons.org/licenses/by-nc-nd/4.0/
      - text: Content licensed under CC BY-NC-SA 4.0
        href: https://creativecommons.org/licenses/by-nc-sa/4.0/
    right: 
      - text: Code samples licensed under the MIT License
        href: https://opensource.org/licenses/MIT

    # left:
    #   - icon: envelope-fill
    #     href: mailto:christian@christianjmills.com
    #   - icon: github
    #     href: https://github.com/cj-mills
    #   - icon: twitter
    #     href: https://twitter.com/cdotjdotmills
    #   - icon: rss
    #     href: index.xml
    # border: false
    background: dark
  back-to-top-navigation: false

  twitter-card:
    creator: "@cdotjdotmills"
    site: "@cdotjdotmills"
    image: images/logo.png
  open-graph:
    image: images/logo.png

format:
  html:
    theme:
      light: custom-flatly.scss
      dark: custom-darkly.scss
    css: styles.css



