project:
  type: website
  # output-dir: docs

website:
  cookie-consent: false
  favicon: images/favicon.ico
  site-url: "christianjmills.com"
  description: "This is Christian Mills' personal Blog."
  title: "Christian Mills"
  image: images/logo.png
  navbar:
    background: dark
    right:
      - text: "Blog"
        file: blog.qmd
      - text: "Tutorials"
        file: series/tutorials/index.md
      - text: "Notes"
        file: series/notes/index.md
      # - icon: file-person-fill
        # href: ./about.html
      # - text: "Services"
      #   file: services.qmd
      - about.qmd
      - icon: envelope-fill
        href: mailto:christian@christianjmills.com
      - icon: github
        href: https://github.com/cj-mills
      # - icon: twitter
      #   href: https://twitter.com/cdotjdotmills
      - icon: linkedin
        href: https://www.linkedin.com/in/christianjmills
      # - icon: discord
      #   href: 
      # - icon: rss
      #   href: blog.xml
  page-navigation: true
  page-footer: 
    center: 
      - text: "Copyright 2024, Christian J. Mills"
    # left:
    #   - icon: envelope-fill
    #     href: mailto:christian@christianjmills.com
    #   - icon: github
    #     href: https://github.com/cj-mills
    #   - icon: twitter
    #     href: https://twitter.com/cdotjdotmills
    #   - icon: rss
    #     href: index.xml
    # border: false
    background: dark
  
  twitter-card:
    creator: "@cdotjdotmills"
    site: "@cdotjdotmills"
    image: images/logo.png
  open-graph:
    image: images/logo.png

format:
  html:
    theme:
      light: custom-flatly.scss
      dark: custom-darkly.scss
    css: styles.css



